WebApplication3/Models/Rezervasyon.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> VarışTarihi { get; set; }
        public Nullable<System.DateTime> AyrılışTarihi { get; set; }
        public string KonukSayısı { get; set; }
        public Nullable<int> OdaTürüid { get; set; }
        public Nullable<int> RezervasyonDurumuid { get; set; }
    }
}

WebApplication3/Controllers/RezervasyonController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class RezervasyonController : Controller
    {
        // GET: Rezervasyon
        public ActionResult Index()
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                var model = db.Rezervasyon.ToList();

                return View(model);
            }

        }
        public ActionResult Create()
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                List<SelectListItem> values = (from x in db.OdaTürü.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.OdaTürü1,
                                                   Value = x.OdaTürüid.ToString()

                                               }).ToList();
                ViewBag.Values = values;

                List<SelectListItem> valuess = (from x in db.RezervasyonDurumu.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = x.RezervasyonDurumu1,
                                                    Value = x.RezervasyonDurumuid.ToString()

                                                }).ToList();
                ViewBag.Valuess = valuess;

                var model = new Rezervasyon();
            }
            return View();

        }
        [HttpPost]
        public ActionResult Create(Rezervasyon rez)
        {

            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    db.Rezervasyon.Add(rez);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(rez);
            }
        }
        public ActionResult Edit(int? id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                List<SelectListItem> values = (from x in db.OdaTürü.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.OdaTürü1,
                                                   Value = x.OdaTürüid.ToString()

                                               }).ToList();
                ViewBag.Values = values;

                List<SelectListItem> valuess = (from x in db.RezervasyonDurumu.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = x.RezervasyonDurumu1,
                                                    Value = x.RezervasyonDurumuid.ToString()

                                                }).ToList();
                ViewBag.Valuess = valuess;



                if (id == null)
                {
                    ViewBag.Uyarı = "Düzenlenecek Hizmet Bulunamadı";
                }
                var kkK = db.Rezervasyon.Find(id);
                if (kkK == null)
                {
                    return HttpNotFound();
                }
                return View(kkK);
            }
        }
        [HttpPost]
        public ActionResult Edit(int? id, Rezervasyon oda)
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    db.Entry(oda).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                if (id == null)
                {

                    return HttpNotFound();

                }
                var hH = db.Rezervasyon.Find(id);
                if (hH == null)
                {
                    return HttpNotFound();
                }
                db.Rezervasyon.Remove(hH);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
        }
    }

}

WebApplication3/Views/Rezervasyon/Create.cshtml
@model WebApplication3.Models.Rezervasyon
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}




<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i>Rezervasyon Formu</h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Create", "Rezervasyon", FormMethod.Post))
                    {
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>
                                <td>Ad</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Ad)
                                </td>
                            </tr>
                            <tr>
                                <td>Soyad</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Soyad)
                                </td>
                            </tr>

                            <tr>
                                <td>Adres</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Adres, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Adres)
                                </td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Email)
                                </td>
                            </tr>
                            <tr>

                                <td>Oda Türü</td>
                                <td>


                                    @Html.DropDownListFor(x => x.OdaTürüid, (List<SelectListItem>)ViewBag.Values, new { @class = "form-control" })
                                </td>
                            </tr>

                            <tr>


                                <td>Rezervasyon Durumu</td>
                                <td>
                                    @Html.DropDownListFor(x => x.RezervasyonDurumuid, (List<SelectListItem>)ViewBag.Valuess, new { @class = "form-control" })
                                </td>
                            </tr>
                            <tr>
                                <td> Varış Tarih</td>
                                <td>
                                    @Html.TextBoxFor(x => x.VarışTarihi, new { @class = " timepicker form-control" })
                                    @Html.ValidationMessageFor(x => x.VarışTarihi)

                                </td>
                            </tr>
                            <tr>
                                <td>Ayrılış Tarihi</td>
                                <td>
                                    @Html.TextBoxFor(x => x.AyrılışTarihi, new { @class = "timepicker form-control" })
                                    @Html.ValidationMessageFor(x => x.AyrılışTarihi)

                                </td>
                            </tr>


                            <tr>
                                <td>Konuk Sayısı</td>
                                <td>
                                    @Html.TextBoxFor(x => x.KonukSayısı, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.KonukSayısı)

                                </td>
                            </tr>



                        </table>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit">Kaydet</button>
                                    <button class="btn btn-danger" type="button"><a href="/Rezervasyon/Index">İptal</button>
                                </div>

                            </div>
                    }
                    </div>
                    
                 
                    
            </div>
        </div>
    </div>
</div>

WebApplication3/Views/Rezervasyon/Edit.cshtml
@model WebApplication3.Models.Rezervasyon
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}




<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i>Rezervasyon Formu</h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Edit", "Rezervasyon", FormMethod.Post))
                    {
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>
                                <td>Ad</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Ad)
                                </td>
                            </tr>
                            <tr>
                                <td>Soyad</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Soyad)
                                </td>
                            </tr>

                            <tr>
                                <td>Adres</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Adres, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Adres)
                                </td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Email)
                                </td>
                            </tr>
                            <tr>

                                <td>Oda Türü</td>
                                <td>


                                    @Html.DropDownListFor(x => x.OdaTürüid, (List<SelectListItem>)ViewBag.Values, new { @class = "form-control" })
                                </td>
                            </tr>

                            <tr>


                                <td>Rezervasyon Durumu</td>
                                <td>
                                    @Html.DropDownListFor(x => x.RezervasyonDurumuid, (List<SelectListItem>)ViewBag.Valuess, new { @class = "form-control" })
                                </td>
                            </tr>
                            <tr>
                                <td> Varış Tarih</td>
                                <td>
                                    @Html.TextBoxFor(x => x.VarışTarihi, new { @class = " timepicker form-control" })
                                    @Html.ValidationMessageFor(x => x.VarışTarihi)

                                </td>
                            </tr>
                            <tr>
                                <td>Ayrılış Tarihi</td>
                                <td>
                                    @Html.TextBoxFor(x => x.AyrılışTarihi, new { @class = "timepicker form-control" })
                                    @Html.ValidationMessageFor(x => x.AyrılışTarihi)

                                </td>
                            </tr>


                            <tr>
                                <td>Konuk Sayısı</td>
                                <td>
                                    @Html.TextBoxFor(x => x.KonukSayısı, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.KonukSayısı)

                                </td>
                            </tr>



                        </table>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/Rezervasyon/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>



            </div>
        </div>
    </div>
</div>

WebApplication3/Views/Rezervasyon/Index.cshtml
@model IEnumerable<WebApplication3.Models.Rezervasyon>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }


    <div id="content-wrapper">
        <div class="container-fluid">


            <div class="card mb-3">
                <div class="card-header">

                    <h4><i class="fas fa-table"></i>Rezervasyon Listesi</h4> <br />
                    <div class="card-header">


                        <a class="btn btn-primary mx-4" href="/Rezervasyon/Create/">Yeni Rezervasyon Ekle</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Ad</th>
                                        <th>Soyad</th>
                                        <th>Adres</th>
                                        <th>Email</th>
                                        <th>Oda Türü</th>
                                        <th>Varış Tarihi</th>
                                        <th>Ayrılış Tarihi</th>
                                        <th>Konuk Sayısı</th>



                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>


                                            <td>@item.Ad</td>
                                            <td>@item.Soyad</td>
                                            <td>@item.Adres</td>
                                            <td>@item.Email</td>
                                            <td>@item.OdaTürüid</td>
                                            <td>@item.VarışTarihi</td>
                                            <td>@item.AyrılışTarihi</td>
                                            <td>@item.KonukSayısı</td>


                                            <td>
                                                <a href="/Rezervasyon/Edit/@item.id" class="btn btn-success">Düzenle</a>|
                                                <a href="/Rezervasyon/Delete/@item.id" class="btn btn-danger"> Sil</a>
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>