WebApplication3/Models/room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int id { get; set; }
        public string Başlık { get; set; }
        public string Resim { get; set; }
        public string Açıklama { get; set; }
        public string Fiyat { get; set; }
    }
}

WebApplication3/Controllers/roomController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class roomController : Controller
    {
        // GET: room
        otelyönetimiEntities db = new otelyönetimiEntities();
        public ActionResult Index()
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                var model = db.room.ToList();

                return View(model);
            }

        }
        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.room, "id", "Başlık", "Açıklama");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(room rez, HttpPostedFileBase Resim)
        {

            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    if (Resim != null)
                    {
                        if (System.IO.File.Exists(Server.MapPath(rez.Resim)))
                        {
                            System.IO.File.Delete(Server.MapPath(rez.Resim));
                        }

                        WebImage img = new WebImage(Resim.InputStream);
                        FileInfo imgİnfo = new FileInfo(Resim.FileName);

                        string resimname = Guid.NewGuid().ToString() + imgİnfo.Extension;
                        img.Resize(50, 100);
                        img.Save("~/Uploads/room/" + resimname);
                        rez.Resim = "/Uploads/room/" + resimname;
                    }


                    db.room.Add(rez);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(rez);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var about = db.room.Where(a => a.id == id).SingleOrDefault();
            return View(about);
        }

        // POST: footer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, room about, HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                var ab = db.room.Where(a => a.id == id).SingleOrDefault();

                if (Resim != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(about.Resim)))
                    {
                        System.IO.File.Delete(Server.MapPath(about.Resim));
                    }

                    WebImage img = new WebImage(Resim.InputStream);
                    FileInfo imgİnfo = new FileInfo(Resim.FileName);

                    string resimname = Guid.NewGuid().ToString() + imgİnfo.Extension;
                    img.Resize(250, 100);
                    img.Save("~/Uploads/room/" + resimname);
                    ab.Resim = "/Uploads/room/" + resimname;
                }
                ab.Başlık = about.Başlık;
                ab.Açıklama = about.Açıklama;
                ab.Fiyat = about.Fiyat;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(about);
        }

        public ActionResult Delete(int id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                if (id == null)
                {

                    return HttpNotFound();

                }
                var hH = db.room.Find(id);
                if (hH == null)
                {
                    return HttpNotFound();
                }
                db.room.Remove(hH);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
        }
    }
}

WebApplication3/Views/room/Create.cshtml
@model WebApplication3.Models.room
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Create", "room", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>ODA TÜRÜ</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Başlık, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Başlık)
                                </td>
                            </tr>

                            <tr>
                                <td>ODA DOTOĞRAFI</td>
                                <td>


                                    <div class="col-md-10">
                                        <input type="file" name="Resim" accept=".jpg,.png,.jpeg" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
                                    </div>

                                </td>
                            </tr>
                            <tr>
                                <td>AÇIKLAMA</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Açıklama, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Açıklama)
                                </td>
                            </tr>
                            <tr>
                                <td>ÜCRET</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Fiyat)
                                </td>
                            </tr>





                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/room/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/room/Edit.cshtml
@model WebApplication3.Models.room
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Edit", "room", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>ODA TÜRÜ</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Başlık, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Başlık)
                                </td>
                            </tr>

                            <tr>
                                <td>ODA DOTOĞRAFI</td>
                                <td>


                                    <div class="col-md-10">
                                        <input type="file" name="Resim" accept=".jpg,.png,.jpeg" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
                                    </div>

                                </td>
                            </tr>
                            <tr>
                                <td>AÇIKLAMA</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Açıklama, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Açıklama)
                                </td>
                            </tr>
                            <tr>
                                <td>ÜCRET</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Fiyat)
                                </td>
                            </tr>





                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/room/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/room/Index.cshtml
@model IEnumerable<WebApplication3.Models.room>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div id="content-wrapper">
    <div class="container-fluid">


        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />

                <div class="card-header">


                    <a class="btn btn-primary mx-4" href="/room/Create/">Yeni Ekle</a>
                </div>


                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ODA TÜRÜ</th>
                                    <th>ODA FOTOĞRAFI</th>
                                    <th>AÇIKLAMA</th>
                                    <th>ÜCRET</th>


                                    <th>İŞLEMLER</th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.Başlık</td>
                                        <td>
                                            <img src="@item.Resim" width="250" height="100" />
                                        </td>
                                        <td>@item.Açıklama</td>
                                        <td>@item.Fiyat</td>


                                        <td>
                                            <a href="/room/Edit/@item.id" class="btn btn-success">Düzenle</a>|
                                            <a href="/room/Delete/@item.id" class="btn btn-danger"> Sil</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>