WebApplication3/Models/footer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class footer
    {
        public int id { get; set; }
        public string Recent_News { get; set; }
        public string For_Customers { get; set; }
        public string Contact_Us { get; set; }
    }
}

WebApplication3/Controllers/footerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class footerController : Controller
    {
        // GET: footer
        public ActionResult Index()
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                var model = db.footer.ToList();

                return View(model);
            }

        }
        public ActionResult Create()
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                var model = new footer();
            }
            return View();

        }
        [HttpPost]
        public ActionResult Create(footer rez)
        {

            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    db.footer.Add(rez);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(rez);
            }
        }
        public ActionResult Edit(int? id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {



                if (id == null)
                {
                    ViewBag.Uyarı = "Düzenlenecek Hizmet Bulunamadı";
                }
                var kkK = db.footer.Find(id);
                if (kkK == null)
                {
                    return HttpNotFound();
                }
                return View(kkK);
            }
        }
        [HttpPost]
        public ActionResult Edit(int? id, footer oda)
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    db.Entry(oda).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                if (id == null)
                {

                    return HttpNotFound();

                }
                var hH = db.footer.Find(id);
                if (hH == null)
                {
                    return HttpNotFound();
                }
                db.footer.Remove(hH);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
        }
    }
}

WebApplication3/Views/footer/Create.cshtml
@model WebApplication3.Models.footer
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i>Footer Ekleme Formu</h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Create", "footer", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>Recent News</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Recent_News, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Recent_News)
                                </td>
                            </tr>

                            <tr>
                                <td>For Customers</td>
                                <td>

                                    @Html.TextBoxFor(x => x.For_Customers, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.For_Customers)
                                </td>
                            </tr>
                            <tr>
                                <td>Contanct Us</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Contact_Us, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Contact_Us)
                                </td>
                            </tr>





                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/footer/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/footer/Edit.cshtml
@model WebApplication3.Models.footer
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i>Footer Ekleme Formu</h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Edit", "footer", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>Recent News</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Recent_News, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Recent_News)
                                </td>
                            </tr>

                            <tr>
                                <td>For Customers</td>
                                <td>

                                    @Html.TextBoxFor(x => x.For_Customers, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.For_Customers)
                                </td>
                            </tr>
                            <tr>
                                <td>Contanct Us</td>
                                <td>
                                    @Html.TextBoxFor(x => x.Contact_Us, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Contact_Us)
                                </td>
                            </tr>





                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/footer/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/footer/Index.cshtml
@model IEnumerable<WebApplication3.Models.footer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div id="content-wrapper">
    <div class="container-fluid">


        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />
                <div class="card-header">


                    <a class="btn btn-primary mx-4" href="/footer/Create/">Yeni Ekle</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>RECENT NEWS</th>
                                    <th>FOR CUSTOMER</th>
                                    <th>CONTANT US</th>


                                    <th>İŞLEMLER</th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.id</td>
                                        <td>@item.Recent_News</td>
                                        <td>@item.For_Customers</td>
                                        <td>@item.Contact_Us</td>


                                        <td>
                                            <a href="/footer/Edit/@item.id" class="btn btn-success">Düzenle</a>|
                                            <a href="/footer/Delete/@item.id" class="btn btn-danger"> Sil</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>