WebApplication3/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class AnasayfaController : Controller
    {
        // GET: Anasayfa
        otelyönetimiEntities db = new otelyönetimiEntities();
        public ActionResult Index()
        {


            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                var model = db.Home.ToList();

                return View(model);
            }

        }

        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Home, "id", "Başlık", "Açıklama");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Home rez, HttpPostedFileBase Resim)
        {

            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {


                if (ModelState.IsValid)
                {


                    if (Resim != null)
                    {
                        if (System.IO.File.Exists(Server.MapPath(rez.Resim)))
                        {
                            System.IO.File.Delete(Server.MapPath(rez.Resim));
                        }

                        WebImage img = new WebImage(Resim.InputStream);
                        FileInfo imgİnfo = new FileInfo(Resim.FileName);

                        string resimname = Guid.NewGuid().ToString() + imgİnfo.Extension;
                        img.Resize(50, 100);
                        img.Save("~/Uploads/anasayfa/" + resimname);
                        rez.Resim = "/Uploads/anasayfa/" + resimname;
                    }


                    db.Home.Add(rez);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(rez);
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var about = db.Home.Where(a => a.id == id).SingleOrDefault();
            return View(about);
        }

        // POST: About/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Home home, HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                var ab = db.Home.Where(a => a.id == id).SingleOrDefault();

                if (Resim != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(home.Resim)))
                    {
                        System.IO.File.Delete(Server.MapPath(home.Resim));
                    }

                    WebImage img = new WebImage(Resim.InputStream);
                    FileInfo imgİnfo = new FileInfo(Resim.FileName);

                    string resimname = Guid.NewGuid().ToString() + imgİnfo.Extension;
                    img.Resize(250, 100);
                    img.Save("~/Uploads/anasayfa/" + resimname);
                    ab.Resim = "/Uploads/anasayfa/" + resimname;
                }
                ab.Başlık = home.Başlık;
                ab.Açıklama = home.Açıklama;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(home);
        }

        public ActionResult Delete(int id)
        {
            using (otelyönetimiEntities db = new otelyönetimiEntities())
            {
                if (id == null)
                {

                    return HttpNotFound();

                }
                var hH = db.Home.Find(id);
                if (hH == null)
                {
                    return HttpNotFound();
                }
                db.Home.Remove(hH);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
        }
    }
}

WebApplication3/Views/Anasayfa/Create.cshtml
@model WebApplication3.Models.Home
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Create", "Anasayfa", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>Başlık</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Başlık, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Başlık)
                                </td>
                            </tr>

                            <tr>
                                <td>Açıklama</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Açıklama, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.Açıklama)
                                </td>
                            </tr>
                            <tr>

                                <td> Resim</td>
                                <td>


                                    <div class="col-md-10">
                                        <input type="file" name="resim" accept=".jpg,.png,.jpeg" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
                                    </div>

                                </td>
                            </tr>
                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/Anasayfa/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/Anasayfa/Edit.cshtml
@model WebApplication3.Models.Home
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div id="content-wrapper">
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @using (Html.BeginForm("Edit", "Anasayfa", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <table class="table table-bordered" width="100%" cellspacing="0">



                            <tr>

                                <td>Başlık</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Başlık, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Başlık)
                                </td>
                            </tr>

                            <tr>
                                <td>Açıklama</td>
                                <td>

                                    @Html.TextBoxFor(x => x.Açıklama, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.Açıklama)
                                </td>
                            </tr>
                            <tr>

                                <td> Resim</td>
                                <td>


                                    <div class="col-md-10">
                                        <input type="file" name="resim" accept=".jpg,.png,.jpeg" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
                                    </div>

                                </td>
                            </tr>
                        </table>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="submit">Kaydet</button>
                                <button class="btn btn-danger" type="button"><a href="/Anasayfa/Index">İptal</button>
                            </div>

                        </div>
                    }
                </div>


            </div>
        </div>
    </div>
</div>

WebApplication3/Views/Anasayfa/Index.cshtml
@model IEnumerable<WebApplication3.Models.Home>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



<div id="content-wrapper">
    <div class="container-fluid">


        <div class="card mb-3">
            <div class="card-header">

                <h4><i class="fas fa-table"></i></h4> <br />
                <div class="card-header">


                    <a class="btn btn-primary mx-4" href="/Anasayfa/Create/">Yeni Ekle</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Başlık</th>
                                    <th>Açıklama</th>

                                    <th>İşlemler</th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.Başlık</td>
                                        <td>@item.Açıklama</td>
                                        <td>
                                            <img src="@item.Resim" width="100" height="100" />
                                        </td>

                                        <td>
                                            <a href="/Anasayfa/Edit/@item.id" class="btn btn-success">Düzenle</a>|
                                            <a href="/Anasayfa/Delete/@item.id" class="btn btn-danger"> Sil</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>